name: everybody_cheese
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.11.0+1
  flutter_signin_button: ^1.0.0
  google_sign_in: ^4.0.11
  firebase_auth: ^0.14.0+5
  firebase_storage: ^3.0.8
  image_picker: ^0.6.2
  carousel_slider: ^1.3.1
  device_info: ^0.4.1+1
  intl: ^0.16.0

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/logo_text.png
    - assets/paris.png
    - assets/zaq.png

  fonts:
    - family: RoundedElegance
      fonts:
        - asset: fonts/RoundedElegance.ttf

    - family: HangeulNuri
      fonts:
        - asset: fonts/HangeulNuriR.ttf
          weight: 400
        - asset: fonts/HangeulNuriB.ttf
          weight: 700

module:
  androidX: true